#!/bin/bash
echo "article-content-writer loaded. Skills available:"
echo "  article-gen — end-to-end long-form article generation with inline image prompts"
echo "  article-validate — five-gate scoring (Quality + Virality + SEO + AI Humanization + GEO) with combined 100-point score"
echo "  article-seo — standalone SEO analysis + optimization (6 metrics, traffic light)"
echo "  article-brief — brainstorm + outline planning with virality pre-assessment"
echo "  article-prep — pipeline-only Steps 1-3 (research+strategy+outline, Sonnet)"
echo "  article-write — pipeline-only Step 4 (write+polish+images, Opus)"
echo "  article-score — pipeline-only Step 5 (five-gate scoring+completion, Sonnet)"
echo ""
echo "Agent available:"
echo "  article-writer — subagent for batch article writing"
echo ""
echo "REMINDER: Read references/global-config.md FIRST for any article generation."
